### ISSUE TITLE
Doesn't detect win on final door obtained through key

### ISSUE THREAD

**Issue by ssmythe** [rfunduk/onirim#1]
Great work on this digital version of Onirim!  Well done!

Think I found a miss in the win logic if you obtain the final door through a key.  Check it out.

![onirim_final_door_ob_through_key_does_not_recognize_win_2016-04-13_11-52-34](https://cloud.githubusercontent.com/assets/3190569/14505514/571c2538-016e-11e6-97e1-8fd2987dd13b.png)

Just obtained the last yellow door, doors show 8/8, but the win condition wasn't detected.

I did draw a card, got a nightmare, used a key on it, and then the game detected the win.  Interesting.

Based on the PDF rules, the victory condition is:

(On page 4 of the PDF)

> The 8 oneiric Doors are the object of your
> quest: having all 8 Door cards on the table is the
> victory condition of the game.

(On page 10 of the PDF)

> C. End of the game
> Victory
> You win if, at any point, all 8 Door cards are in play at the same time. The game ends immediately
> (you don’t have to replenish your hand).

So I think whenever the door count is 8/8, the victory condition is met regardless of the current hand state, yeah?

Really enjoying your very clean implementation.  Thank you for putting it together!

**Comment by rfunduk** [comment]
You are completely right! Thanks a lot for pointing it out. Added a test to confirm and fixed it :+1:
